const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('pikpak', {
  getAccount: () => ipcRenderer.invoke('account:get'),
  getAccountAbout: () => ipcRenderer.invoke('account:about'),
  onAccountExpired: callback => { const listener=()=>callback(); ipcRenderer.on('account:expired',listener); return ()=>ipcRenderer.removeListener('account:expired',listener); },
  setAccessToken: token => ipcRenderer.invoke('account:set-token', token),
  login: () => ipcRenderer.invoke('account:login'),
  logout: () => ipcRenderer.invoke('account:logout'),
  listDrive: parentId => ipcRenderer.invoke('drive:list', parentId),
  searchDrive: query => ipcRenderer.invoke('drive:search', query),
  cancelSearch: () => ipcRenderer.invoke('drive:search-cancel'),
  onSearchProgress: callback => { const listener=(_event,value)=>callback(value); ipcRenderer.on('search:progress',listener); return ()=>ipcRenderer.removeListener('search:progress',listener); },
  getDriveFile: id => ipcRenderer.invoke('drive:file-info', id),
  listStarred: () => ipcRenderer.invoke('starred:list'),
  listRecent: () => ipcRenderer.invoke('recent:list'),
  setStarred: payload => ipcRenderer.invoke('drive:star', payload),
  createFolder: payload => ipcRenderer.invoke('drive:create-folder', payload),
  rename: payload => ipcRenderer.invoke('drive:rename', payload),
  trash: id => ipcRenderer.invoke('drive:trash', id),
  transfer: payload => ipcRenderer.invoke('drive:transfer', payload),
  listTrash: () => ipcRenderer.invoke('trash:list'),
  restoreTrash: id => ipcRenderer.invoke('trash:restore', id),
  deleteTrash: id => ipcRenderer.invoke('trash:delete', id),
  openShare: url => ipcRenderer.invoke('share:open', url),
  getShareFile: payload => ipcRenderer.invoke('share:file-info', payload),
  restoreShare: payload => ipcRenderer.invoke('share:restore', payload),
  createShare: payload => ipcRenderer.invoke('share:create', payload),
  listMyShares: () => ipcRenderer.invoke('shares:list'),
  cancelShares: ids => ipcRenderer.invoke('shares:cancel', ids),
  copyShare: item => ipcRenderer.invoke('shares:copy', item),
  createOfflineTask: url => ipcRenderer.invoke('offline:create', url),
  listOfflineTasks: () => ipcRenderer.invoke('offline:list'),
  deleteOfflineTask: id => ipcRenderer.invoke('offline:delete', id),
  startDownload: payload => ipcRenderer.invoke('download:start', payload),
  chooseUpload: payload => ipcRenderer.invoke('upload:choose', payload),
  chooseUploadFolder: payload => ipcRenderer.invoke('upload:choose-folder', payload),
  uploadDroppedFiles: (files,payload={}) => ipcRenderer.invoke('upload:paths',{...payload,paths:Array.from(files||[]).map(file=>webUtils.getPathForFile(file)).filter(Boolean)}),
  cancelUpload: id => ipcRenderer.invoke('upload:cancel', id),
  retryUpload: id => ipcRenderer.invoke('upload:retry', id),
  listUploads: () => ipcRenderer.invoke('upload:list'),
  removeUpload: id => ipcRenderer.invoke('upload:remove', id),
  clearUploads: () => ipcRenderer.invoke('upload:clear'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  chooseDownloadDirectory: () => ipcRenderer.invoke('settings:choose-download-dir'),
  saveSettings: value => ipcRenderer.invoke('settings:set', value),
  resetSettings: () => ipcRenderer.invoke('settings:reset'),
  exportDiagnostics: () => ipcRenderer.invoke('app:export-diagnostics'),
  onUpload: callback => { const listener=(_event,value)=>callback(value); ipcRenderer.on('upload:event',listener); return ()=>ipcRenderer.removeListener('upload:event',listener); },
  openViewer: payload => ipcRenderer.invoke('viewer:open', payload),
  listArchive: payload => ipcRenderer.invoke('archive:list', payload),
  cancelDownload: id => ipcRenderer.invoke('download:cancel', id),
  retryDownload: id => ipcRenderer.invoke('download:retry', id),
  showDownload: path => ipcRenderer.invoke('download:show', path),
  listDownloads: () => ipcRenderer.invoke('download:list'),
  removeDownload: id => ipcRenderer.invoke('download:remove', id),
  clearDownloads: () => ipcRenderer.invoke('download:clear'),
  onDownload: callback => { const listener=(_event,value)=>callback(value); ipcRenderer.on('download:event',listener); return ()=>ipcRenderer.removeListener('download:event',listener); }
});
